<?php

if (!defined('NGCMS')) die ('HAL');

$result = array (
  0 => 
  array (
    'id' => '1',
    'parent' => '0',
    'title' => 'Флудиловка',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '1',
    'avatar' => NULL,
  ),
  1 => 
  array (
    'id' => '12',
    'parent' => '1',
    'title' => 'Немного по флудим',
    'description' => 'Общаемся на все темы',
    'keywords' => '',
    'lock_passwd' => '',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '1',
    'int_post' => '1',
    'l_post' => '1',
    'l_date' => '1392640587',
    'l_topic_id' => '1',
    'l_topic_title' => 'Тестовая тема',
    'l_author' => 'irbees2008',
    'l_author_id' => '1',
    'position' => '1',
    'avatar' => '1.31738.gif',
  ),
  2 => 
  array (
    'id' => '13',
    'parent' => '2',
    'title' => 'Все что знаете ,помните о Шахтинске',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '1',
    'avatar' => NULL,
  ),
  3 => 
  array (
    'id' => '14',
    'parent' => '3',
    'title' => 'Кто что продает?',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '2',
    'int_post' => '2',
    'l_post' => '3',
    'l_date' => '1448661966',
    'l_topic_id' => '3',
    'l_topic_title' => 'Продам оперативку',
    'l_author' => 'Админ',
    'l_author_id' => '45',
    'position' => '1',
    'avatar' => '',
  ),
  4 => 
  array (
    'id' => '15',
    'parent' => '4',
    'title' => 'Хочу купить',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '1',
    'avatar' => NULL,
  ),
  5 => 
  array (
    'id' => '16',
    'parent' => '5',
    'title' => 'Меняемся',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '1',
    'avatar' => NULL,
  ),
  6 => 
  array (
    'id' => '17',
    'parent' => '6',
    'title' => 'Сдам',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '1',
    'avatar' => NULL,
  ),
  7 => 
  array (
    'id' => '18',
    'parent' => '7',
    'title' => 'Возьму в аренду',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '1',
    'avatar' => NULL,
  ),
  8 => 
  array (
    'id' => '19',
    'parent' => '8',
    'title' => 'просто общаемся на жизненые вопросы',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '1',
    'avatar' => NULL,
  ),
  9 => 
  array (
    'id' => '20',
    'parent' => '9',
    'title' => 'Обсуждаем ваши авто',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '1',
    'avatar' => NULL,
  ),
  10 => 
  array (
    'id' => '21',
    'parent' => '10',
    'title' => 'Кто что читает?',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '1',
    'avatar' => NULL,
  ),
  11 => 
  array (
    'id' => '22',
    'parent' => '11',
    'title' => 'Делимся секретами мастерства',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '',
    'redirect_url' => '',
    'moderators' => 'N;',
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '1',
    'avatar' => NULL,
  ),
  12 => 
  array (
    'id' => '2',
    'parent' => '0',
    'title' => 'Шахтинск',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '2',
    'avatar' => NULL,
  ),
  13 => 
  array (
    'id' => '3',
    'parent' => '0',
    'title' => 'Продам',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '3',
    'avatar' => NULL,
  ),
  14 => 
  array (
    'id' => '4',
    'parent' => '0',
    'title' => 'Куплю',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '4',
    'avatar' => NULL,
  ),
  15 => 
  array (
    'id' => '5',
    'parent' => '0',
    'title' => 'Обменяю',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '5',
    'avatar' => NULL,
  ),
  16 => 
  array (
    'id' => '6',
    'parent' => '0',
    'title' => 'Сдам в аренду',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '6',
    'avatar' => NULL,
  ),
  17 => 
  array (
    'id' => '7',
    'parent' => '0',
    'title' => 'Возьму в аренду',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '7',
    'avatar' => NULL,
  ),
  18 => 
  array (
    'id' => '8',
    'parent' => '0',
    'title' => 'О жизни',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '8',
    'avatar' => NULL,
  ),
  19 => 
  array (
    'id' => '9',
    'parent' => '0',
    'title' => 'О машинах',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '9',
    'avatar' => NULL,
  ),
  20 => 
  array (
    'id' => '10',
    'parent' => '0',
    'title' => 'О книгах',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '10',
    'avatar' => NULL,
  ),
  21 => 
  array (
    'id' => '11',
    'parent' => '0',
    'title' => 'Секреты',
    'description' => '',
    'keywords' => '',
    'lock_passwd' => '0',
    'redirect_url' => NULL,
    'moderators' => NULL,
    'int_topic' => '0',
    'int_post' => '0',
    'l_post' => '0',
    'l_date' => '0',
    'l_topic_id' => '0',
    'l_topic_title' => '',
    'l_author' => '',
    'l_author_id' => '0',
    'position' => '11',
    'avatar' => NULL,
  ),
);

