<?php

if (!defined('NGCMS')) die ('HAL');

$FORUM_PERM = array (
  0 => 
  array (
    12 => 
    array (
      'id' => '1',
      'group_id' => '0',
      'forum_id' => '12',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    13 => 
    array (
      'id' => '7',
      'group_id' => '0',
      'forum_id' => '13',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    14 => 
    array (
      'id' => '13',
      'group_id' => '0',
      'forum_id' => '14',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    15 => 
    array (
      'id' => '19',
      'group_id' => '0',
      'forum_id' => '15',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    16 => 
    array (
      'id' => '25',
      'group_id' => '0',
      'forum_id' => '16',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    17 => 
    array (
      'id' => '31',
      'group_id' => '0',
      'forum_id' => '17',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    18 => 
    array (
      'id' => '37',
      'group_id' => '0',
      'forum_id' => '18',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    19 => 
    array (
      'id' => '43',
      'group_id' => '0',
      'forum_id' => '19',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    20 => 
    array (
      'id' => '49',
      'group_id' => '0',
      'forum_id' => '20',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    21 => 
    array (
      'id' => '55',
      'group_id' => '0',
      'forum_id' => '21',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    22 => 
    array (
      'id' => '61',
      'group_id' => '0',
      'forum_id' => '22',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '0',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
  ),
  1 => 
  array (
    12 => 
    array (
      'id' => '2',
      'group_id' => '1',
      'forum_id' => '12',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
    13 => 
    array (
      'id' => '8',
      'group_id' => '1',
      'forum_id' => '13',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
    14 => 
    array (
      'id' => '14',
      'group_id' => '1',
      'forum_id' => '14',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
    15 => 
    array (
      'id' => '20',
      'group_id' => '1',
      'forum_id' => '15',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
    16 => 
    array (
      'id' => '26',
      'group_id' => '1',
      'forum_id' => '16',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
    17 => 
    array (
      'id' => '32',
      'group_id' => '1',
      'forum_id' => '17',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
    18 => 
    array (
      'id' => '38',
      'group_id' => '1',
      'forum_id' => '18',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
    19 => 
    array (
      'id' => '44',
      'group_id' => '1',
      'forum_id' => '19',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
    20 => 
    array (
      'id' => '50',
      'group_id' => '1',
      'forum_id' => '20',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
    21 => 
    array (
      'id' => '56',
      'group_id' => '1',
      'forum_id' => '21',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
    22 => 
    array (
      'id' => '62',
      'group_id' => '1',
      'forum_id' => '22',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '1',
      'topic_modify_your' => '1',
      'topic_closed' => '1',
      'topic_closed_your' => '1',
      'topic_remove' => '1',
      'topic_remove_your' => '1',
      'post_send' => '1',
      'post_modify' => '1',
      'post_modify_your' => '1',
      'post_remove' => '1',
      'post_remove_your' => '1',
    ),
  ),
  2 => 
  array (
    12 => 
    array (
      'id' => '3',
      'group_id' => '2',
      'forum_id' => '12',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    13 => 
    array (
      'id' => '9',
      'group_id' => '2',
      'forum_id' => '13',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    14 => 
    array (
      'id' => '15',
      'group_id' => '2',
      'forum_id' => '14',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    15 => 
    array (
      'id' => '21',
      'group_id' => '2',
      'forum_id' => '15',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    16 => 
    array (
      'id' => '27',
      'group_id' => '2',
      'forum_id' => '16',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    17 => 
    array (
      'id' => '33',
      'group_id' => '2',
      'forum_id' => '17',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    18 => 
    array (
      'id' => '39',
      'group_id' => '2',
      'forum_id' => '18',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    19 => 
    array (
      'id' => '45',
      'group_id' => '2',
      'forum_id' => '19',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    20 => 
    array (
      'id' => '51',
      'group_id' => '2',
      'forum_id' => '20',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    21 => 
    array (
      'id' => '57',
      'group_id' => '2',
      'forum_id' => '21',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    22 => 
    array (
      'id' => '63',
      'group_id' => '2',
      'forum_id' => '22',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
  ),
  3 => 
  array (
    12 => 
    array (
      'id' => '4',
      'group_id' => '3',
      'forum_id' => '12',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    13 => 
    array (
      'id' => '10',
      'group_id' => '3',
      'forum_id' => '13',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    14 => 
    array (
      'id' => '16',
      'group_id' => '3',
      'forum_id' => '14',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    15 => 
    array (
      'id' => '22',
      'group_id' => '3',
      'forum_id' => '15',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    16 => 
    array (
      'id' => '28',
      'group_id' => '3',
      'forum_id' => '16',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    17 => 
    array (
      'id' => '34',
      'group_id' => '3',
      'forum_id' => '17',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    18 => 
    array (
      'id' => '40',
      'group_id' => '3',
      'forum_id' => '18',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    19 => 
    array (
      'id' => '46',
      'group_id' => '3',
      'forum_id' => '19',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    20 => 
    array (
      'id' => '52',
      'group_id' => '3',
      'forum_id' => '20',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    21 => 
    array (
      'id' => '58',
      'group_id' => '3',
      'forum_id' => '21',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    22 => 
    array (
      'id' => '64',
      'group_id' => '3',
      'forum_id' => '22',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
  ),
  4 => 
  array (
    12 => 
    array (
      'id' => '5',
      'group_id' => '4',
      'forum_id' => '12',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    13 => 
    array (
      'id' => '11',
      'group_id' => '4',
      'forum_id' => '13',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    14 => 
    array (
      'id' => '17',
      'group_id' => '4',
      'forum_id' => '14',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    15 => 
    array (
      'id' => '23',
      'group_id' => '4',
      'forum_id' => '15',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    16 => 
    array (
      'id' => '29',
      'group_id' => '4',
      'forum_id' => '16',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    17 => 
    array (
      'id' => '35',
      'group_id' => '4',
      'forum_id' => '17',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    18 => 
    array (
      'id' => '41',
      'group_id' => '4',
      'forum_id' => '18',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    19 => 
    array (
      'id' => '47',
      'group_id' => '4',
      'forum_id' => '19',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    20 => 
    array (
      'id' => '53',
      'group_id' => '4',
      'forum_id' => '20',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    21 => 
    array (
      'id' => '59',
      'group_id' => '4',
      'forum_id' => '21',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
    22 => 
    array (
      'id' => '65',
      'group_id' => '4',
      'forum_id' => '22',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '1',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '1',
      'post_remove' => '0',
      'post_remove_your' => '1',
    ),
  ),
  5 => 
  array (
    12 => 
    array (
      'id' => '6',
      'group_id' => '5',
      'forum_id' => '12',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    13 => 
    array (
      'id' => '12',
      'group_id' => '5',
      'forum_id' => '13',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    14 => 
    array (
      'id' => '18',
      'group_id' => '5',
      'forum_id' => '14',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    15 => 
    array (
      'id' => '24',
      'group_id' => '5',
      'forum_id' => '15',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    16 => 
    array (
      'id' => '30',
      'group_id' => '5',
      'forum_id' => '16',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    17 => 
    array (
      'id' => '36',
      'group_id' => '5',
      'forum_id' => '17',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    18 => 
    array (
      'id' => '42',
      'group_id' => '5',
      'forum_id' => '18',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    19 => 
    array (
      'id' => '48',
      'group_id' => '5',
      'forum_id' => '19',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    20 => 
    array (
      'id' => '54',
      'group_id' => '5',
      'forum_id' => '20',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    21 => 
    array (
      'id' => '60',
      'group_id' => '5',
      'forum_id' => '21',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
    22 => 
    array (
      'id' => '66',
      'group_id' => '5',
      'forum_id' => '22',
      'forum_read' => '1',
      'topic_read' => '1',
      'topic_send' => '0',
      'topic_modify' => '0',
      'topic_modify_your' => '0',
      'topic_closed' => '0',
      'topic_closed_your' => '0',
      'topic_remove' => '0',
      'topic_remove_your' => '0',
      'post_send' => '1',
      'post_modify' => '0',
      'post_modify_your' => '0',
      'post_remove' => '0',
      'post_remove_your' => '0',
    ),
  ),
);

