name: Build source code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-cache search php && sudo apt-get install php7.3

      - name: Install composer
        run: |
          curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

      - name: Download source code
        run: |
          mkdir ~/build
          git clone https://github.com/vponomarev/ngcms-core build/
          git clone https://github.com/vponomarev/ngcms-plugins build/engine/plugins/
          cd ~/build
          ls -lA

      - name: Install libraries via composer
        run: |
          cd ~/build
          ls -lA
          composer install

      - name: Make package
        uses: actions/upload-artifact@master
        with:
          name: ngcms-current-build
          path: build
