name: Build source code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Download source code
        run: |
          mkdir ~/build
          git clone https://github.com/vponomarev/ngcms-core build/
          git clone https://github.com/vponomarev/ngcms-plugins build/engine/plugins/

      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-cache search php && sudo apt-get install php7.3
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          cd ~/build
          composer install

      - name: Make package
        uses: actions/upload-artifact@master
        with:
          name: ngcms-current-build
          path: build
